export type SignalType = 'BUY' | 'STRONG BUY' | 'WAIT' | 'AVOID' | 'DATA UNAVAILABLE';
export type MarketRegime = 'RISK ON' | 'NEUTRAL' | 'RISK OFF' | 'PRE-MARKET' | 'MARKET CLOSED';
export type MarketSessionStatus = 'TOKYO MARKET OPEN' | 'TOKYO MARKET CLOSED' | 'PTS SESSION' | 'US MARKET OPEN' | 'US MARKET CLOSED' | 'PRE-MARKET';
export type PtsSignalType = 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE' | 'DATA UNAVAILABLE';
export type DataQuality = 'LIVE' | 'RECENT' | 'DELAYED' | 'STALE' | 'ERROR' | 'UNAVAILABLE' | 'DEMO';
export type PtsDataQuality = 'LIVE' | 'RECENT' | 'STALE' | 'ERROR' | 'UNAVAILABLE' | 'DEMO';
export type NewsSentiment = 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE';
export type DropReason = 'NEWS-DRIVEN DROP' | 'MARKET-WIDE DROP' | 'TECHNICAL DROP' | 'UNKNOWN' | 'NONE';
export interface OHLCV { time:string; timestamp:number; open:number; high:number; low:number; close:number; volume:number; vwap:number; ma20?:number; ma75?:number; }
export interface PreviousCloseData { price:number; date:string; benchmarkDescription:string; source:string; }
export type PrevCloseInfo = PreviousCloseData;
export interface TokyoMarketData { price:number; change:number; changePercent:number; open:number; high:number; low:number; volume:number; vwap:number; lastUpdated:string; dataQuality:DataQuality; source:string; isMarketOpen:boolean; }
export type TokyoMarketPriceInfo = TokyoMarketData;
export interface PTSDebugPipelineInfo { symbol:string; source:string; market:string; sourceRawSnippet:string; parsedPrice:number|null; parsedChange:number|null; parsedChangePercent:number|null; parsedTradeTime:string|null; validationStatus:'VALID'|'INVALID'|'OUT_OF_BOUNDS'|'EMPTY'; validationMessage:string; validatedPrice:number|null; cachedAtTimestamp:number; cacheAgeSeconds:number; fetchedAt:string; apiResponseStatus:string; }
export interface PtsHistoryPoint { date:string; time:string; timestamp:number; price:number; changeVsPrevClose:number; changePercentVsPrevClose:number; volume:number; turnover?:number; market:string; source:string; }
export interface PTSMarketData { isAvailable:boolean; market:string; price:number; change:number|null; changePercent:number|null; changeVsPrevClose:number; changePercentVsPrevClose:number; diffVsTokyoPrice:number; diffPercentVsTokyoPrice:number; tradeTimestamp:string|null; tradeTime:string; fetchedAt:string; lastUpdated:string; cachedAt?:number; cacheAgeSeconds?:number; open:number|null; high:number|null; low:number|null; volume:number|null; turnover:number|null; marketName:string; source:string; status:'ACTIVE_TRADING'|'LAST_PTS_TRADE'|'PTS_SESSION_CLOSED'|'DATA_UNAVAILABLE'|'NO_RECENT_TRADE'|'PTS_DATA_INVALID'; dataQuality:'LIVE'|'RECENT'|'STALE'|'UNAVAILABLE'|'INVALID'; closeStatus:'ACTIVE_TRADING'|'PTS SESSION CLOSE'|'LAST PTS TRADE'|'PTS SESSION CLOSED'; unavailableReason?:string; warningNote?:string; ptsSignal:PtsSignalType; surgeOrDropStatus:'SURGE'|'DROP'|'NORMAL'|'NONE'; surgePercent?:number; historicalPoints?:PtsHistoryPoint[]; validSampleCount?:number; debugInfo?:PTSDebugPipelineInfo; driverClassification?:{type:'NEWS'|'US_SEMI'|'UNKNOWN';title:string;explanation:string}; nextDayOpenAnalysis?:{directionText:string;disclaimer:string;sampleCount:number;isSufficientSample:boolean;historicalStats?:{upPercent:number;flatPercent:number;downPercent:number}}; }
export type PtsMarketPriceInfo = PTSMarketData;
export interface KioxiaMarketData { symbol:string; name:string; price:number; change:number; changePercent:number; open:number; high:number; low:number; prevClose:number; vwap:number; volume:number; avg20dVolume:number; volumeRatioVs20d:number; rsi14:number; macd:{macdLine:number;signalLine:number;histogram:number}; ma5:number; ma20:number; ma25:number; ma75:number; atr14:number; prevHigh:number; prevLow:number; intraday5m:OHLCV[]; hourly1h:OHLCV[]; daily1d:OHLCV[]; dataFreshness:DataQuality; lastUpdated:string; isMarketOpen:boolean; isPreMarket:boolean; marketSession:MarketSessionStatus; prevCloseInfo:PrevCloseInfo; tokyoMarketInfo:TokyoMarketPriceInfo; ptsMarketInfo:PtsMarketPriceInfo; }
export interface UsSemiQuote { symbol:string; name:string; price:number; change:number; changePercent:number; afterHoursPrice?:number; afterHoursChangePercent?:number; lastUpdated:string; freshness:'LIVE'|'MINUTES_AGO'|'DELAYED'|'FAILED'|'DEMO'; category:'CHIP'|'MEMORY'|'INDEX'|'MACRO'|'FX'; details?:{nextEarningsDate?:string;revenueConsensus?:string;epsConsensus?:string;source?:string;updatedAt?:string}; }
export interface NewsItem { id:string; title:string; translatedTitle?:string; summary:string; source:string; publishedAt:string; sentiment:NewsSentiment; importance:'HIGH'|'MEDIUM'|'LOW'; kioxiaImpact:string; tags:string[]; url?:string; }
export interface ScoreBreakdown { technical:number; technicalMax:40; usSemi:number; usSemiMax:25; aiMemory:number; aiMemoryMax:15; japanFx:number; japanFxMax:10; news:number; newsMax:10; total:number; details:{technicalNotes:string[];usSemiNotes:string[];aiMemoryNotes:string[];japanFxNotes:string[];newsNotes:string[]}; }
export interface BuyCandidates { primaryMin:number; primaryMax:number; primaryRationale:string; secondaryMin:number; secondaryMax:number; secondaryRationale:string; }
export interface ChasingRiskAssessment { isHighRisk:boolean; score:number; triggers:string[]; recommendation:string; }
export interface DropAssessment { isDrop:boolean; reason:DropReason; dropPercent:number; analysis:string; }
export interface DayTimeCell { day:'MON'|'TUE'|'WED'|'THU'|'FRI'; timeSlot:string; avgReturnToClose:number; winRate:number; sampleCount:number; avgVolatility:number; }
export interface DayStats { dayName:string; avgReturn:number; winRate:number; avgRange:number; avgVolume:number; first30mReturn:number; first60mReturn:number; morningReturn:number; afternoonReturn:number; eodReturn:number; }
export interface SimilarScenarioResult { matchConditions:{day:string;time:string;kioxiaGainPercent:number;vwapRelation:'ABOVE'|'BELOW';volumeSpikeRatio:number;soxGainPercent:number;nvdaGainPercent:number}; sampleCount:number; isSampleSufficient:boolean; outcomes:{plus30m:{avgReturn:number;winRate:number};plus60m:{avgReturn:number;winRate:number};plus120m:{avgReturn:number;winRate:number};eod:{avgReturn:number;winRate:number}}; }
export interface AiCommentResult { comment:string; rationale:string[]; keyRisks:string[]; confidence:number; generatedAt:string; }
export interface PortfolioPosition { id:string; symbol:string; name:string; sector:string; buyPrice:number; shares:number; currentPrice:number; note?:string; }
export interface AlertRule { id:string; type:'PRICE_BELOW'|'PRICE_ABOVE'|'SCORE_ABOVE'|'VOLUME_SPIKE'|'NVDA_SPIKE'; threshold:number; enabled:boolean; label:string; }
export type DataOrigin = 'REAL'|'SYNTHETIC'|'SIMULATED'|'DEMO'|'MOCK'|'ESTIMATED'|'UNKNOWN';
export interface RealPtsRecord { date:string; symbol:string; market:string; ptsPrice:number; previousClose:number; ptsChangePercent:number; tradeTimestamp:string; nextTradingDay:string; nextOpen:number; nextClose:number; source:string; status:'VALID'|'STALE'|'UNAVAILABLE'|'OUT_OF_BOUNDS'; dataOrigin:DataOrigin; triggerScore?:number; }
export interface PtsBinBacktest { rangeLabel:string; sampleCount:number; guRate:number; gdRate:number; flatRate:number; avgReturn:number; medianReturn:number; maxGain:number; maxLoss:number; confidenceStatus:'INSUFFICIENT SAMPLE'|'LOW CONFIDENCE'|'STATISTICALLY USABLE'; }
export interface SignalComparisonSummary { signal:'BUY'|'WAIT'|'SELL'; count:number; winRate:number; avgReturn:number; medianReturn:number; maxDrawdown:number; confidenceStatus:'INSUFFICIENT SAMPLE'|'LOW CONFIDENCE'|'STATISTICALLY USABLE'; }
export interface BacktestResult { period:'1M'|'3M'|'6M'|'1Y'; sampleCount:number; winRate:number; avgReturn:number; medianReturn:number; totalReturn:number; maxProfit:number; maxLoss:number; profitFactor:number; maxDrawdown:number; expectedValue:number; sharpeRatio:number; confidenceStatus:'INSUFFICIENT SAMPLE'|'LOW CONFIDENCE'|'STATISTICALLY USABLE'; feePercent:number; slippagePercent:number; ptsBins:PtsBinBacktest[]; signalComparisons:SignalComparisonSummary[]; equityCurve:{date:string;equity:number}[]; trades:{date:string;entryPrice:number;exitPrice:number;pnlPercent:number;holdingHours:number;triggerScore:number;ptsChangePercent:number}[]; }
